### ISSUE TITLE
Brew installing Spectral timing out and not able to download

### ISSUE THREAD

**Issue by alexander-blackwell** [aaronraimist/homebrew-tap#1]
Getting 502 bad gateway on https://dl.bintray.com/encombhat/Spectral/spectral-0.0.0.605.dmg

curl: (22) The requested URL returned error: 502                              
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
curl: (22) The requested URL returned error: 502                              
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
curl: (22) The requested URL returned error: 502                              
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
curl: (22) The requested URL returned error: 502                              

Error: Download failed on Cask 'spectral' with message: Download failed: https://dl.bintray.com/encombhat/Spectral/spectral-0.0.0.605.dmg

**Comment by aaronraimist** [comment]
Bintray shut down a while back so that's probably why the links have stopped working. I'm not sure if there is any other place to get Spectral builds. I don't think Spectral is actively maintained nowadays.
